---
uplink_interface:
  - {int: "ethernet1/10", ip: 192.168.7.2/24, des: To spine_1}
  - {int: "ethernet1/12", ip: 192.168.2.2/30, des: To spine_2}

hostports:
   - { int: "ethernet1/5", des: ESXI-1, vlan: 20, state: present }
   - { int: "ethernet1/6", des: ESXI-2, vlan: 20, state: present }
   - { int: "ethernet1/7", des: Openstack-nova-server-1, vlan: 60, state: default}
   - { int: "ethernet1/8", des: Openstack-nova-server-2, vlan: 60, state: absent }
